### PR TITLE
change verb from lend to borrow

### LINKED ISSUE #5: Change lending to borrow?
It sounds a bit weird in my head to say lending all the time. It's more common to say borrow as the verb.

### PR DESCRIPTION
**Pull request by AsLogd**
## Which issue(s) this PR fixes (optional) 

Fixes #5 

## Some questions
- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct
- [x] I understand that my PR won't be merged until Travis gives a "green light"

## Additional Notes (optional)
Other pending PR's may need a refactor after merging this one

### CODE REVIEW

**Review by qaisjp — COMMENTED** [review]
Might be useful to tweak the migration file to rename instead of losing data

**Comment by AsLogd** [comment]
Good point. I didn't know that was possible

**Comment by casassg** [comment]
Will wait for that to accept it first :P

**Comment by AsLogd** [comment]
Quick question: Given that this project is still not being used, how bad would it be to just remove migrations and start over?

**Comment by qaisjp** [comment]
Personally I would say it is bad but not the end of the world. 

[FYI i found this](https://stackoverflow.com/questions/25091130/django-migration-strategy-for-renaming-a-model-and-relationship-fields)

**Comment by AsLogd** [comment]
Haha yeah I checked that but it looked like more time than I can spend. I will fix this on the weekend. Thanks

**Review by ofpau — APPROVED** [review]

**Pull request merged**
